### ISSUE TITLE
Cannot view Elmah logs

### ISSUE THREAD

**Issue by pendraggon87** [RehanSaeed/ASP.NET-MVC-Boilerplate#12]
When clicking on detail for an error in elmah, I get a 500 error.  When viewing elmah, I get the following error message: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

Is this due to how the template is configured?

**Comment by RehanSaeed** [comment]
This bug was fixed last week and was wild for a couple of days so you were a bit unlucky. The problem lay in the RedirectToCanonicalUrlAttribute. We had to put in a check specifically to handle Elmah pages. You can take a look at the code I updated [here](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/Source/MvcBoilerplate/Framework/RedirectToCanonicalUrlAttribute.cs)
