### ISSUE TITLE
AppendTrailingSlash = false breaks web site

### ISSUE THREAD

**Issue by safepage** [RehanSaeed/ASP.NET-MVC-Boilerplate#25]
Hi, changing the AppendTrailingSlash value to false breaks the web site, i.e home page returns "This page can’t be displayed".

I appreciate this is your preferred choice, but it would be good if it worked both ways.

Thanks

**Comment by RehanSaeed** [comment]
You are correct, that should work. I'll take a look this evening as to why it is failing.

**Comment by safepage** [comment]
MVC 5

**Comment by RehanSaeed** [comment]
I've made an update to the Boilerplate.Web.Mvc5 NuGet package. Could you please update to version 1.0.20 and confirm that all is well so I can update the project template to use the new version.

Interestingly, the bug was only affecting the home page. I should not have added or removed a trailing slash for the home page as both are equivalent. Web browsers seem to behave differently too depending on which one you use.
