### ISSUE TITLE
Generation of Icon Set

### ISSUE THREAD

**Issue by xiecsuk** [RehanSaeed/ASP.NET-MVC-Boilerplate#3]
I have used http://realfavicongenerator.net/ to generate my set of icons using my own graphic and they have generated extremely well. However, It has generated some icons that are not in the set originally provided and there are more in the original set that have not been generated. For instance, none of the apple-touch-startup-image files have been generated.

Is any of this important?

**Comment by RehanSaeed** [comment]
That is a really good site and one I used to get started. It does not support splash screen images however which is why ASP.NET MVC Boilerplate has apple-touch-startup-image files. 

It seems they have added other files since I last looked into this subject. I'll review their changes and see if they can be added to ASP.NET MVC Boilerplate.

**Comment by RehanSaeed** [comment]
Ok, so I've now taken a look and it's all pretty interesting. There are a raft of new icons for Android/Chrome M39+. More details in the links below:

http://realfavicongenerator.net/blog/welcome-android-chrome/
https://developer.chrome.com/multidevice/android/installtohomescreen#supporting
http://updates.html5rocks.com/2014/11/Support-for-theme-color-in-Chrome-39-for-Android
