### ISSUE TITLE
Purpose of the constants

### ISSUE THREAD

**Issue by pendraggon87** [RehanSaeed/ASP.NET-MVC-Boilerplate#36]
Is there a purpose behind using the constants? It seems that this takes more time in development, and precludes being able to use ROUTE("") for the Index action of a controller?

**Comment by RehanSaeed** [comment]
There are two reasons.

1. We use named routes instead of controller name and action name. This has better performance. So `Url.RouteUrl("RouteName")` is quicker than `Url.Action("Controller", "Action")`.

2. What happens when you've finished your application, you are using strings everywhere and now you want to rename a controller or action? You have to go through all the views looking for any string that has the old controller or action name. Having constants allows Visual Studio to do all the work and lets us rename the constant easily.

**Comment by mcquiggd** [comment]
@RehanSaeed 

If you are interested, I have created T4 Templates to automatically generate the Constants for:

Controller Names
'Action' Names, which detect if an HTTPGet or HTTPost, or a Route definition attribute was applied and creates constants accordingly. 
View Names
I have others for creating constants for content files - e.g. CSS, Images, JavaScripts etc.

If you are interested, let me know and I will add a sample on GitHub to see what you think.
